
version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c-app-vendas-herc
    ports:
      - "3133:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: mariadb:10.3
    container_name: c-mariadb-vendas-herc
    environment:
      - MYSQL_ROOT_PASSWORD=bsi-vendas
    ports:
      - "3134:3306"
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: c-phpmyadmin-vendas-herc
    environment:
      - MYSQL_ROOT_PASSWORD=bsi-vendas
    ports:
      - "3135:80"
